### ISSUE TITLE
BUG - Plugins that break when reloading

### ISSUE THREAD

**Issue by TecEash1** [gnmyt/MCDash#101] opened 2023-11-20 22:04 UTC
When reloading the server via a timed schedule the orebfuscator and ProtocolLIB plugin break. The only way to fix it is my clicking the ‘restart’ button for me.

**Comment by PrettyBlueSkye** [comment] 2023-11-24 19:59
this is with  almost all plugins. that's why when you run /reload you have to do /reload confirm. its not supported. the best way to "reload" is just restart the server. its nothing you can do to fix it as its a internal thing with paper/plugin server jar you are using and the plugins

**Comment by gnmyt** [comment] 2023-11-25 10:18
Hi, thanks for reporting this. As @PrettyBlueSkye already said, this can happen when reloading instead of restarting. I'm closing this issue as it's not really related to MCDash, but if you think the plugin is the cause of your problem, feel free to reopen this issue and attach some logs :)

**Closed by gnmyt** 2023-11-25 10:18 UTC
