### ISSUE TITLE
Cannot use the web console

### ISSUE THREAD

**Issue by I2000C** [gnmyt/MCDash#23] opened 2023-07-19 10:43 UTC
When the server starts, this warning appears in the console:
![image](https://github.com/gnmyt/MCDash/assets/29607352/0707d912-3ffe-467e-8bd8-8e1690e87714)

Then, if I want to use the web console, an error appears:
![image](https://github.com/gnmyt/MCDash/assets/29607352/cb8bc640-3521-41d7-9b78-fc03de2a4e28)

and a large error is shown in the local console:
![image](https://github.com/gnmyt/MCDash/assets/29607352/5de16d41-532e-43d4-b710-8a8dca4e2144)

Note: I'm using Spigot 1.8.8

**Comment by gnmyt** [comment] 2023-07-19 12:22
Hey, thanks for reporting this. I need some additional information to reproduce this issue.

- Which Java version are you using?
- Have you tried to connect to the console via the SSH server? If so, does the same problem occur?
- Does the server log file `logs/latest.log` exist?
- Are you using a Windows or Linux server?

**Comment by I2000C** [comment] 2023-07-19 13:26
Java version: 8
Console through SSH: is working (with some delay, but working)
logs/latest.log: exists
server: Windows

**Comment by I2000C** [comment] 2023-07-23 11:35
I think I have found the problem.
When I set the `enable-query` option to `true`, the console started working:
![image](https://github.com/gnmyt/MCDash/assets/29607352/5fb09f82-3d62-4d5f-82b7-54c6e9c07e6a)

![image](https://github.com/gnmyt/MCDash/assets/29607352/ca57ba0f-94ed-48b2-861a-07dcfcd376b4)

However, the warning still appears: 
![image](https://github.com/gnmyt/MCDash/assets/29607352/efd0e526-7194-4782-aeef-381a4070052c)
and if I send a command, there's an extra warning:
![image](https://github.com/gnmyt/MCDash/assets/29607352/c02c5d5d-9a16-4a06-8062-175dde0c4a3d)

**Comment by marcjoancr** [comment] 2023-07-27 09:02
Error still continues after enabling `enable-query`, I have the same exact error described in the issue.

**Comment by gnmyt** [comment] 2023-07-27 16:25
The extra warning when sending commands [is intended](https://github.com/gnmyt/MCDash/blob/55fbbb8bc44e19ed5044aa13e8d252756b883c2c/src/main/java/de/gnmyt/mcdash/panel/routes/ConsoleRoute.java#L52). I couldn't replicate the issue on my machines but since ssh worked I'm just gonna use the logic from there and implement it in the web route. It should be fixed in the next version (1.1.5)

**Comment by gnmyt** [comment] 2023-08-14 11:04
I have opened a PR for this (#30). As soon as the new version (1.1.5) is available, the problem should be solved. If not, I would appreciate it if you would just reopen this issue. Thanks :)

**Closed** 2023-08-14 11:42 UTC
Labels: bug
